Add cms 1
aichner/Ukiyo pull request #2
Opened 2020-05-19 21:07 UTC by Aichnerc

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no Firebase integration.
- Currently there is no data being fetched from Firebase.
- Currently the login is not working.
- Currently the HomePage is our template.

**What is the new behavior (if this is a feature change)?**
- Firebase has been initiated.
- The page can now be fetched from Firebase.
- You can now login.
- The HomePage is now the latest published page.

2020-05-19 21:16 UTC, Aichnerc reviewed
Mmm. 👀

2020-05-19 21:16 UTC, Aichnerc commented on src/store/actions/pageActions.js
> +          return data;
Add new line.

2020-05-19 21:16 UTC, Aichnerc commented on src/store/reducers/pageReducer.js
> +      console.log("Error", action.err);
Is this `console.log();` really needed?

2020-05-19 21:57 UTC, kleberbaum requested changes
Should be ok to merge after a few changes.

2020-05-19 21:57 UTC, kleberbaum commented on src/store/actions/pageActions.js
> +//#endregion
Please add a newline.

2020-05-20 07:38 UTC, Aichnerc commented on src/store/reducers/pageReducer.js
> +      console.log("Error", action.err);
Yep.

2020-05-20 07:56 UTC, LucaAllmaier approved these changes
Looks good to me.

2020-05-20 08:29 UTC, schettn requested changes
Check for console logs and for missing new lines then it should be on a good way.

2020-05-20 08:29 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +    console.log(page);
Is this still needed?

2020-05-20 08:29 UTC, schettn commented on src/components/pages/HomePage/index.jsx
> +      console.log(sections);
Is this still needed?

2020-05-20 08:29 UTC, schettn commented on src/components/pages/ProfilePage/index.jsx
> +      console.log(latestVersion);
Is this still needed?

2020-05-20 08:29 UTC, schettn commented on src/components/pages/ProfilePage/index.jsx
> +    //this.props.getPage();
Is this still needed?

2020-05-20 08:29 UTC, schettn commented on src/store/actions/pageActions.js
> +        );
add newline

2020-05-20 13:33 UTC, Aichnerc commented on src/components/pages/HomePage/index.jsx
> +    console.log(page);
Yep

2020-05-20 13:33 UTC, Aichnerc commented on src/components/pages/ProfilePage/index.jsx
> +      console.log(latestVersion);
Yep

2020-05-20 13:33 UTC, Aichnerc commented on src/components/pages/HomePage/index.jsx
> +      console.log(sections);
Yep

2020-05-20 13:34 UTC, Aichnerc commented on src/components/pages/ProfilePage/index.jsx
> +    //this.props.getPage();
Yep

2020-05-20 13:49 UTC, schettn approved these changes
Yep

2020-05-20 15:14 UTC, kleberbaum approved these changes
Should be ok to merge.

2020-05-20 15:17 UTC, merged